### ISSUE TITLE
Importing is taking more then a minute

### ISSUE THREAD

**Issue by sathi081289** [Pamblam/mysql-import#10]
Hi , 
I am using your package. it is working awesome but it takes more then a minute.
 
How to reduce the time ?

**Comment by Pamblam** [comment]
If you can provide an example of an import that takes a long time i can see what i can do about improving it.

**Comment by sathi081289** [comment]
Hi Pamblam, 
thanks for your response. following the actual code for importing tables.

schoolimport.js

MysqlInfo = {
dbhost: 'localhost',
username: 'root',
password: '',
dbname: 'school'
}
sqlfilename = 'schooldb.sql'

mysqlDump({
    connection: {
      host: MysqlInfo.dbhost,
      user: MysqlInfo.username,
      password: MysqlInfo.password,
      database: MysqlInfo.dbname
    },
    dump: {
      tables: tablenames,
      excludeTables: false,
      schema: {
        autoIncrement: true,
        table: {
          ifNotExist: false,
          dropIfExist: true
        }
      },
      data: {
        format: true,
        maxRowsPerInsertStatement: 10000
      },
      trigger: false
    },
    dumpToFile: "./SyncTables/" + sqlfilename
  })
    .then(dump => {
      mysqlimport
        .config({
          host: MysqlInfo.dbhost,
          user: MysqlInfo.username,
          password: MysqlInfo.password,
          database: schoolDbname,
          onerror: err => console.log(err.message)
        })
        .import("./SyncTables/" + sqlfilename)
        .then(() => {
          callback(null, {
            Status: true,
            StatusCode: 202,
            message: "School Tables Sync done successfully"
          });
        })
        .catch(error => {
          console.log(error);
          callback(error);
        });
    })
    .catch(err => {
      callback(err);
    });

the import db size is 132kb. it takes almost 1 minute to import the tables.

**Comment by Pamblam** [comment]
thanks but that isn't going to help, i need an import file. as in the sql file that is being parsed.

**Comment by sathi081289** [comment]
following is the import file.
[school.zip](https://github.com/Pamblam/mysql-import/files/3175789/school.zip)

**Comment by Pamblam** [comment]
thank you. that helps. maybe adding an option to ignore line breaks would speed things up. mind if i ask how you exported this?

**Comment by GauravKanted** [comment]
Hi @Pamblam , apologies for the late reply. I'm replying on behalf of @sathi081289 .
We exported the file using [mysqldump](https://www.npmjs.com/package/mysqldump) package available for node.js.  
Could you maybe elaborate on what you mean by "adding an option to ignore line breaks" ?
TIA!

**Comment by WooDzu** [comment]
I had similar issue recently and found this little optimization helps with parsing large sql files:
https://github.com/Pamblam/mysql-import/pull/14/files

In my use case I had a 5MB mysqldump file that took 10 minutes to parse/process. Now it only takes a few seconds.

**Comment by GauravKanted** [comment]
Hi @WooDzu  Thanks for the reply.
I saw the commit and have implemented it in my local repo, But it's still taking longer than a minute for a 200kb sql dump.

**Comment by WooDzu** [comment]
Does the SQL include any form of a `DELEMITER` ? Can't think what else could be affecting it.

**Comment by GauravKanted** [comment]
Hi I'm attaching the sql file for your reference. I don't see any problems with it.
[impSql.zip](https://github.com/Pamblam/mysql-import/files/3425029/impSql.zip)

**Comment by GauravKanted** [comment]
Hey any updates on this issue? @Pamblam @WooDzu 
Do let me know if you need any more details.

**Comment by Pamblam** [comment]
@GauravKanted, @WooDzu submitted PR #14 which should help. Feel free to re-open if you continue to have issues.
