### ISSUE TITLE
[change request] reuse importer

### ISSUE THREAD

**Issue by jjangga0214** [Pamblam/mysql-import#12]
Hi, @Pamblam.
Thank you for this library.
 
When I reuse the importer object, the error below occurs.
```js
await importer.import("foo.sql");
await importer.import("bar.sql"); // this causes error.
```
```bash
Cannot enqueue Query after invoking quit.
```
So users have to make exact same numbers of importer with .sql files.
For convenience, I do something like this.

```js
function importer() {
  return mysql_import.config({
    host: 'HOST',
    database: 'DATABASE
    user: 'USER',
    password: 'PASSWORD'
  });
}

await importer().import("foo.sql");
await importer().import("bar.sql");
```

I feel inconvenience and personnally think the API has two problems.

1. Not intuitive. I think many people aren't familar with (and thus do not intuitively expect) providing connection information every time they communicate with database.
2. Performance. We might be able to enhance speed (in certain condition) if we reuse database connection.

How do you think about it? If you think so, we can make some breaking changes on it.

Thanks :)

**Comment by NealMastel** [comment]
I second this, same importer to multiple imports would be nice!
