### ISSUE TITLE
[feature request] multiple files in same directory, multiple imports

### ISSUE THREAD

**Issue by jjangga0214** [Pamblam/mysql-import#13]
I believe organizing .sql files in the same directory is quite common. 
And for some cases (including mine), someone might want them to be executed altogether. 

For example, when using mysql docker image, every .sh and .sql files attached in **/docker-entrypoint-initdb.d** are executed in alphanumeric order at the time of booting. [1] 

So, we might think of something like below.

# Proposals 

## Directory as an Argument

When argument of `import` is directory, then import every .sql files in it with alphanumeric order.
```js
importer.import('<DIRECTORY>'); 
```

## Multiple Arguments

We can also provide an explicit way of importing multiple files
The below would import "foo.sql", "bar.sql" and every .sql files in the "\<DIRECTORY\>".

```js
importer.import([ 'foo.sql', 'bar.sql', '<DIRECTORY>']); 
```
    
    
    
How do you feel? Maybe I could be making a PR for it/them, if you think this idea is good.   

##### refs

- [1] "Initializing a fresh instance" <https://hub.docker.com/_/mysql>

**Comment by Pamblam** [comment]
That is a great idea! I've got my hands full at the moment but I will get this done when time allows!
