### ISSUE TITLE
Getting ER_NOT_SUPPORTED_AUTH_MODE error with MySQL 8.0.19

### ISSUE THREAD

**Issue by mat-berg** [Pamblam/mysql-import#26]
mysql-import version: 3.0.6
mysql version: 8.0.19

Getting 

> Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

Did try to execute the following query on the mysql server with no success
`ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'mypassword';`

Any ideas on what could be the issue? Should mysql-import consider using mysql2 instead?

**Comment by mat-berg** [comment]
Seams to be a limitation from mysql module not supporting caching_sha2_password. Will change to user to mysql_native_password.

**Comment by sonickseven** [comment]
> Seams to be a limitation from mysql module not supporting caching_sha2_password. Will change to user to mysql_native_password.

is a problem when we used docker :/

**Comment by Pamblam** [comment]
Yeah, nothing we can do until the mysql module is updated. Not an issue with this module.

https://stackoverflow.com/questions/50373427/node-js-cant-authenticate-to-mysql-8-0
