### ISSUE TITLE
It does not import functions

### ISSUE THREAD

**Issue by viktor-voicenter** [Pamblam/mysql-import#27]
I have been looking at code. It does not process begin end constructions at all. My problem that I tried to resolve by your library is described [here](https://stackoverflow.com/questions/60373216/restore-mysql-sql-dump-by-nodejs-without-mysqldump).

**Comment by Pamblam** [comment]
Hi Viktor

Please provide an example of a function that won't import. Currently, apparently, [the issue cannot be duplicated](https://stackoverflow.com/questions/60373216/restore-mysql-sql-dump-by-nodejs-without-mysqldump#comment106804436_60373216). If you provide steps to duplicate the issue, including sample SQL I will fix it.

Thanks
