### ISSUE TITLE
When the .sql file is larger than 2GB, fs will throw error "RangeError [ERR_FS_FILE_TOO_LARGE]"

### ISSUE THREAD

**Issue by coffeeeeffoc** [Pamblam/mysql-import#32]
When the .sql file is larger than 2GB, fs will throw error "RangeError [ERR_FS_FILE_TOO_LARGE]: File size (5067659903) is greater than possible Buffer: 2147483647 bytes".
That is the max buffer size in node. To import larger files, the code will need to change the imports to streams instead of putting the whole file in a buffer?

**Comment by Pamblam** [comment]
You're right. If you're interested in sendnig me a PR that would be awesome, otherwise I'll fix it as soon as I get some time.

**Comment by Pamblam** [comment]
Version 5.0 now uses streams instead of writing the entire dump files into memory. Issue resolved.
