### ISSUE TITLE
Improving Doc

### ISSUE THREAD

**Issue by michaelscheurer** [Pamblam/mysql-import#4]
It would be nice to complete the documentation with a liddle detail, that can help saving time:

The import() method needs the path to the file as an argument rather than the filename. This can be achieved by adding __dirname to import(__dirname + '/file.sql')

It's maybe worth to mention it in the documentation and adding it to the example code.

cheers

**Comment by Pamblam** [comment]
you would think that should go without saying. it's just node, not magic. feel free to submit a PR if you would like.
