### ISSUE TITLE
cannot set custom mysql tcp port

### ISSUE THREAD

**Issue by sirber** [Pamblam/mysql-import#43]
there is no constructor parameter, and host:port does not work

**Comment by Thomas-1985** [comment]
Same issue here, would be important to be fixed please

**Comment by MattContassot** [comment]
would be a great feature to change the default port

**Comment by Pamblam** [comment]
You can add a `port` option to the constructor, as well as any other parameters [listed here](https://github.com/mysqljs/mysql#connection-options). I've updated the documentation to explain that.
