### ISSUE TITLE
Cannot find module 'mysql-import'

### ISSUE THREAD

**Issue by eramudeep** [Pamblam/mysql-import#44]
Error: Cannot find module 'mysql-import'
Require stack:
- /Applications/Legitquest.app/Contents/Resources/app.asar/app/electron/HasMySql.js
- /Applications/Legitquest.app/Contents/Resources/app.asar/app/electron/preload.js

My **preload.js** 
`
const { contextBridge, ipcRenderer } = require("electron");
const fs = require("fs");
const i18nextBackend = require("i18next-electron-fs-backend");
const Store = require("secure-electron-store").default;
const ContextMenu = require("secure-electron-context-menu").default;
const getmac = require("getmac");
const {
  runImportDump,
  HasMySql,
  createDatabse,
  readData,
} = require("./HasMySql");`

My **HasMySql.js** begain with 
`var mysql = require("mysql");
const getmac = require("getmac");
const databasePrefix = "amusoftech_";
const Importer = require("mysql-import");`

**Error thrown** : Error: Cannot find module 'mysql-import'

**Comment by Pamblam** [comment]
Node dependencies don't work like PHP dependencies. You need to require the dependency in every file that needs it.

You need to put `var Importer = require("mysql-import");` in any file that needs to use the `Importer` object.
