### ISSUE TITLE
Add option for removing existing db content before import

### ISSUE THREAD

**Issue by Thomas-1985** [Pamblam/mysql-import#48]
Hi

I am using mysql-import for a Node.js/Express project, but am missing an option that allows me to completely remove the contents of the old db before importing a new db with mysql-import.

I tried to import a db over and existing half-corrupted one and got errors. If i clean the old db before the import, it works

Best,
Thomas

**Comment by Pamblam** [comment]
Having this as an option in this package would require this package to include a tokenizer and alter your queries for you. That's beyond the scope of this project, but it's easy enough to do this on your own.

 1. Add the mysql package to your project: `npm install mysql`
 2. Require the package in your script: `const mysql = require('mysql');`
 3. Grab the helper functions out of the `test/test-helpers.js` file.
 4. Use the `query` function to drop or truncate your table or database before importing.
