### ISSUE TITLE
5.0.21 onProgress() not working

### ISSUE THREAD

**Issue by Thomas-1985** [Pamblam/mysql-import#49]
Hi

I am using this example to import a database in my Node/Express app

`
const host = 'localhost';
const user = 'root';
const password = 'password';
const database = 'mydb';

const Importer = require('mysql-import');
const importer = new Importer({host, user, password, database});

// New onProgress method, added in version 5.0!
importer.onProgress(progress=>{
  var percent = Math.floor(progress.bytes_processed / progress.total_bytes * 10000) / 100;
  console.log(`${percent}% Completed`);
});

importer.import('path/to/dump.sql').then(()=>{
  var files_imported = importer.getImported();
  console.log(`${files_imported.length} SQL file(s) imported.`);
}).catch(err=>{
  console.error(err);
});
`

However i don't get any console messages about the percentage completed.

What am i doing wrong?

Best,
Thomas

**Comment by Pamblam** [comment]
There are a few issues with your code:

 1. Use `127.0.0.1` instead of `localhost` for your host.
 2. Use your correct credentials. Hopefully your password isn't actually "password".
 3. Quote your strings. There's a syntax error in your code, which may just be an artifact of copy/paste.

The following code is confirmed to work. If you're still having issues please provide more detail on how to reproduce the problem.

```js
const host = '127.0.0.1'; // <-- Use 127.0.0.1 instead of "localhost"
const user = 'root';
const password = '';  // <-- Enter your password
const database = 'mydb';

const Importer = require('../mysql-import');
const importer = new Importer({host, user, password, database});

importer.onProgress(progress=>{
	var percent = Math.floor(progress.bytes_processed / progress.total_bytes * 10000) / 100;
	console.log(`${percent}% Completed`); // <-- Make sure your quote your string
});

importer.import('/Users/rob/htdocs/mysql-import/test/sample_dump_files/test.sql').then(()=>{
	var files_imported = importer.getImported();
	console.log(`${files_imported.length} SQL file(s) imported.`);  // <-- Make sure your quote your string
}).catch(err=>{
	console.error(err);
});
```
