### ISSUE TITLE
Close the connection after the query finished

### ISSUE THREAD

**Issue by navy0333** [Pamblam/mysql-import#5]
Hey there, nice work!
I've notice that your library doesn't have function to close the connection, giving `Error: read ECONNRESET` for those who set their mysql timeouts.
This makes running multiple sql files at the same time hassle, if I have three files with different length of rows, the one who's shortest will finish first, triggering `ECONNRESET` that makes the server reset and other queries stop.

Thanks for the hard work! I really appreciate it 👏

**Comment by joshcoales** [comment]
I've just spent a good while trying to track down an unclosed resource, and finally pinned it down to this library. Please can you add this, I've managed to work around it with this:

```
const importer = require("mysql-import").config({
    host: config["mysql"]["host"],
    user: config["mysql"]["username"],
    password: config["mysql"]["password"],
    database: "zoo_species_test"
});
importer.import("sql/zoo_species_test.sql").then(function (a) {
    importer.conn.end();
    console.log("Imported test mysql database.");
});
```

But yes, please close the connection after import, and thank you so much for this package!

**Comment by Pamblam** [comment]
Thanks for finding that that! Fixed.
