### ISSUE TITLE
Store procedures and triggers error

### ISSUE THREAD

**Issue by leonardospeca** [Pamblam/mysql-import#7]
I'm exporting a dumb .sql file from phpmyadmin (tried from Mysql Workbench, too). It contains creation of tables, store procedures and triggers. If I import that file from phpmyadmin there is no problem, using the library it throws and error:

> ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `manage...

Tried to comment store procedures and triggers and everything worked fine

**Comment by Pamblam** [comment]
Hi @leonardospeca - Would you mind showing the specific SQL that is causing the problems?

**Comment by leonardospeca** [comment]
sure!

**test.sql**
`SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

DELIMITER $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `test`(IN `test` INT)
    DETERMINISTIC
SELECT 1$$

DELIMITER ;

CREATE TABLE IF NOT EXISTS `test` (
  `test` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
`

**index.js**
`const mysql_import = require('mysql-import');

var importer = mysql_import.config({
	host: '...',
	user: '...',
	password: '...',
	database: 'test',
	onerror: err=>console.log(err.message)
});

importer.import('test.sql').then(()=> {
	console.log('DB1 has finished importing')
});
`
[test.txt](https://github.com/Pamblam/mysql-import/files/2906926/test.txt)
[index.txt](https://github.com/Pamblam/mysql-import/files/2906930/index.txt)

**Comment by leonardospeca** [comment]
Ps. congrats for the work, is really helpful

**Comment by leonardospeca** [comment]
Any ideas?

**Comment by Pamblam** [comment]
Sorry fort he delay, busy with work stuff.

I've completely re-written the parser for the second time published it as version 2. I've added your scenario to the unit testing as well. Code coverage has jumped from 94% to 98%.

Thank you
