### ISSUE TITLE
Missing promise resolution on error

### ISSUE THREAD

**Issue by onexdata** [Pamblam/mysql-import#9]
Hi, awesome work!  I'm using your package in a remote query admin tool; an admin presses a button, an RPC is fired, it calls sql-import, but the await never returns if there is an error... instead, the onerror function is called in the config, which seems the best I can manage out of this.

However, this doesn't work for most use cases; the unresolved promise on error will cause memory build-up and eventually crash Node, also, the onerror func can only return a new call to the client... it can't respond to the old one (i.e. it can only return from itself, it can't trigger a return on the parent call.

All this would be solved with a promise... await...resolve...reject pattern; Can we make it so it rejects the promise on error instead of the onerror config option?

**Comment by onexdata** [comment]
For example, change this:

```
	import(filename){
		return new Promise(done=>{
			var queriesString = fs.readFileSync(filename, 'utf8');
			var queries = new queryParser(queriesString).queries;
			slowLoop(queries, (q,i,d)=>{
				try{
					this.conn.query(q, err=>{
						/* istanbul ignore next */
						if (err) this.err_handler(err); 
						else d();
					});
				}catch(e){
					/* istanbul ignore next */
					this.err_handler(e); 
				}
			}).then(()=>{
				this.conn.end();
				done();
			});
		});
	}
```

...to this...

```
	import(filename){
		return new Promise((resolve, reject) => {
			var queriesString = fs.readFileSync(filename, 'utf8');
			var queries = new queryParser(queriesString).queries;
			slowLoop(queries, (q,i,d)=>{
				try{
					this.conn.query(q, err=>{
						/* istanbul ignore next */
						if (err) {
              this.err_handler(err);
              reject(err);
            }
            else {
              d();
            }
					});
				}catch(e){
					/* istanbul ignore next */
					this.err_handler(e); 
				}
			}).then(()=>{
				this.conn.end();
				resolve('Success!');
			});
		});
	}
```

Now people can use mysql-import like this, without defining an error handler...

```
 let result = await mysqlImport
    .config(options)
    .import(path.join(__dirname, `/query.sql`))
    .then(e => {
      return 'it worked!'
    }).catch(e => {
      return `It failed! Reason: ${e}`
    });
```

**Comment by Pamblam** [comment]
well, the `catch` is the error handler. this is more or less sugar but i'll do it.

**Comment by Pamblam** [comment]
fixed in v4
